### ISSUE TITLE
When launching `npm run dev`, jsx error is shown

### ISSUE THREAD

**Issue by arryon** [JMPerez/c#2]
I like your initiative for this collaborative app :). However, from the master branch I can't launch a working application. I'm using node v8.9 and ran `npm install` from the source dir. After `npm run dev` webpack compiles succesfully but an error occurs at the web page:

```
StyleSheet: `insertRule` accepts only strings.
Error: StyleSheet: `insertRule` accepts only strings.
    at invariant (/Users/arryon/projects/c-spotify/node_modules/styled-jsx/dist/lib/stylesheet.js:274:11)
    at StyleSheet.insertRule (/Users/arryon/projects/c-spotify/node_modules/styled-jsx/dist/lib/stylesheet.js:125:7)
    at /Users/arryon/projects/c-spotify/node_modules/styled-jsx/dist/stylesheet-registry.js:88:29
    at Array.map (<anonymous>)
    at StyleSheetRegistry.add (/Users/arryon/projects/c-spotify/node_modules/styled-jsx/dist/stylesheet-registry.js:87:27)
    at JSXStyle.componentWillMount (/Users/arryon/projects/c-spotify/node_modules/styled-jsx/dist/style.js:58:26)
    at resolve (/Users/arryon/projects/c-spotify/node_modules/react-dom/cjs/react-dom-server.node.development.js:2119:12)
    at ReactDOMServerRenderer.render (/Users/arryon/projects/c-spotify/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/arryon/projects/c-spotify/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/Users/arryon/projects/c-spotify/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
```

Searching a bit yielded This issue: https://github.com/zeit/next.js/issues/3442

Seems like what you're doing (defining styles in the render() function) is no longer supported by next.

**Comment by JMPerez** [comment]
@arryon Thanks for reporting it! Unfortunately I don't have much time these days to fix these issues. It would be great if you (or anyone else reading this) could contribute back with a PR.

**Comment by arryon** [comment]
I would love to, but I'm missing the required expertise with React to be able to pinpoint the exact origin of the error (which component etc). I'm currently trying an older commit from this repo to see if I can get a working app to start with.

Do you have tips for debugging in such a way that I can see in which component the jsx style errors?

**Comment by arryon** [comment]
Can confirm that your initial 'Push project' commit works, besides #1 where indeed prop-types@15.5.10 and jsx-styles@1.0.8 were missing from package.json.

**Comment by cavpollo** [comment]
[Here is a PR](https://github.com/JMPerez/c/pull/4) to fix the bug :slightly_smiling_face:

**Comment by JMPerez** [comment]
Should be fixed by https://github.com/JMPerez/c/pull/4
